### ISSUE TITLE
No upload in anaconda

### ISSUE THREAD

**Issue by pradal** [openalea/action-build-publish-anaconda#2]
I do not see any upload in anaconda.

See https://github.com/openalea/weberpenn

**Comment by thomasarsouze** [comment]
Oops. My bad ! Please switch to action version 0.1.1

**Comment by pradal** [comment]
I first switch, and have an error: 
https://github.com/openalea/weberpenn/runs/5857999125?check_suite_focus=true

I try to add the label explicitly.

**Comment by pradal** [comment]
Upload package conda-build-dir.MHxhtm/linux-64/openalea.weberpenn-2.1.0-0.tar.bz2 to anaconda with label main on channel associated to the given token.
  Using Anaconda API: https://api.anaconda.org/
  Error:  ('Authorization header was not given', 401)
  Error: Process completed with exit code 1.

**Comment by thomasarsouze** [comment]
I think this is because you're trying to use the openalea token from your "pradal" branch in your merge request... You should copy the token from anaconda to your "pradal" github account. Not sure though, but I let you try this workaround.

This means that so far, this only works on pull request from branches inside the openalea project. I don't know how bad this situation is...

**Comment by pradal** [comment]
Thxs.
I will merge the branch and test it
